FROM node:18-alpine AS builder
WORKDIR /
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:18-alpine
WORKDIR /
COPY --from=builder /dist ./dist
COPY package*.json ./
RUN npm ci --only=production
EXPOSE 3001
CMD ["npm", "start"]